export const FETCH_CARDS_PENDING = 'FETCH_CARDS_PENDING';
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
export const FETCH_CARDS_ERROR = 'FETCH_CARDS_ERROR';
export const UPDATE_CARDS = 'UPDATE_CARDS';
export const DELETE_CARDS = 'DELETE_CARDS';
